// app/api/admin/customers/route.ts
import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/app/lib/supabase'
import { requireAdmin } from '@/app/lib/admin-auth'

export async function GET(req: NextRequest) {
  try {
    // Check admin authentication
    await requireAdmin()

    const { searchParams } = new URL(req.url)
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '50')
    const sortBy = searchParams.get('sortBy') || 'created_at'
    const sortOrder = searchParams.get('sortOrder') || 'desc'

    const offset = (page - 1) * limit

    console.log(`🔍 ADMIN: Fetching all customers (page ${page}, limit ${limit})`)

    // Get total count
    const { count: totalCount, error: countError } = await supabaseAdmin
      .from('profiles')
      .select('*', { count: 'exact', head: true })

    if (countError) {
      console.error('Error getting total count:', countError)
    }

    // Get customers with subscriptions
    const { data: customers, error: customersError } = await supabaseAdmin
      .from('profiles')
      .select(`
        id,
        clerk_user_id,
        email,
        full_name,
        plan,
        license_key,
        stripe_customer_id,
        created_at,
        updated_at,
        subscriptions (
          id,
          stripe_subscription_id,
          status,
          plan_id,
          current_period_start,
          current_period_end,
          trial_end,
          cancel_at_period_end,
          created_at,
          updated_at
        ),
        app_usage (
          memory_scans_performed,
          memory_freed_mb,
          apps_optimized,
          last_active,
          total_usage_time_minutes
        )
      `)
      .order(sortBy, { ascending: sortOrder === 'asc' })
      .range(offset, offset + limit - 1)

    if (customersError) {
      console.error('🚨 ADMIN: Customers fetch error:', customersError)
      return NextResponse.json({
        success: false,
        error: 'Failed to fetch customers'
      }, { status: 500 })
    }

    // Format the results with revenue calculations
    const formattedCustomers = customers?.map(customer => {
      const subscription = Array.isArray(customer.subscriptions) 
        ? customer.subscriptions[0] 
        : customer.subscriptions

      const usage = Array.isArray(customer.app_usage)
        ? customer.app_usage[0]
        : customer.app_usage

      // Calculate total revenue generated by this customer
      const calculateRevenue = () => {
        if (!subscription) return 0
        
        const createdAt = new Date(subscription.created_at)
        const updatedAt = new Date(subscription.updated_at)
        const now = new Date()
        
        // Calculate months between subscription start and now (or when it ended)
        const endDate = subscription.status === 'canceled' ? updatedAt : now
        const monthsActive = Math.max(1, Math.floor((endDate.getTime() - createdAt.getTime()) / (1000 * 60 * 60 * 24 * 30)))
        
        if (subscription.plan_id === 'pro_monthly') {
          return monthsActive * 4.99
        } else if (subscription.plan_id === 'pro_yearly') {
          const yearsActive = Math.max(1, Math.floor(monthsActive / 12))
          return yearsActive * 39.99
        }
        
        return 0
      }

      return {
        id: customer.id,
        clerkUserId: customer.clerk_user_id,
        email: customer.email,
        name: customer.full_name,
        plan: customer.plan,
        licenseKey: customer.license_key,
        stripeCustomerId: customer.stripe_customer_id,
        createdAt: customer.created_at,
        updatedAt: customer.updated_at,
        
        subscription: subscription ? {
          id: subscription.id,
          stripeSubscriptionId: subscription.stripe_subscription_id,
          status: subscription.status,
          planId: subscription.plan_id,
          currentPeriodStart: subscription.current_period_start,
          currentPeriodEnd: subscription.current_period_end,
          trialEnd: subscription.trial_end,
          cancelAtPeriodEnd: subscription.cancel_at_period_end,
          createdAt: subscription.created_at
        } : null,
        
        usage: usage ? {
          scansPerformed: usage.memory_scans_performed || 0,
          memoryFreed: usage.memory_freed_mb || 0,
          appsOptimized: usage.apps_optimized || 0,
          lastActive: usage.last_active,
          totalUsageTime: usage.total_usage_time_minutes || 0
        } : null,
        
        // Computed fields
        isPro: subscription?.status === 'active' || subscription?.status === 'trialing',
        isTrialing: subscription?.status === 'trialing',
        daysSinceSignup: Math.floor((Date.now() - new Date(customer.created_at).getTime()) / (1000 * 60 * 60 * 24)),
        totalRevenue: calculateRevenue(),
        subscriberSince: subscription?.created_at ? new Date(subscription.created_at).toLocaleDateString() : null
      }
    }) || []

    console.log(`✅ ADMIN: Found ${formattedCustomers.length} customers`)

    return NextResponse.json({
      success: true,
      customers: formattedCustomers,
      pagination: {
        page,
        limit,
        total: totalCount || 0,
        totalPages: Math.ceil((totalCount || 0) / limit),
        hasNext: offset + limit < (totalCount || 0),
        hasPrev: page > 1
      },
      sorting: {
        sortBy,
        sortOrder
      }
    })

  } catch (error) {
    console.error('🚨 ADMIN: All customers API error:', error)
    
    return NextResponse.json({
      success: false,
      error: error.message || 'Failed to fetch customers'
    }, { status: error.message?.includes('Unauthorized') ? 403 : 500 })
  }
}